theme: jekyll-theme-cayman
title: "CS 194/294-267 Understanding Large Language Models: Foundations and Safety"
description: Spring 2024
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-redirect-from
