theme: jekyll-theme-cayman
title: | 
  "CS 194/294-196 Decentralized Intelligence:
  Large Language Model Agents"
description: Spring 2024
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-redirect-from
